### ISSUE TITLE
{crew}: a distributed computing worker framework built on {mirai}

### ISSUE THREAD

**Issue by wlandau** [cran-task-views/HighPerformanceComputing#11]
May I submit a PR to add [`crew`](https://wlandau.github.io/crew/)? It extends [`mirai`](https://github.com/shikokuchuo/mirai) with auto-scaling, a central manager, and a framework for user-defined plugins to run tasks on different platforms and services.

**Comment by eddelbuettel** [comment]
Sure -- saw your tweets and toots.  You can see (and, I believe, know) the format.  Short and concise, in the correct section, and most likely at the end of the section unless to want to add to an existing bullet point.

I actually do my work upstream [at this repo](https://github.com/eddelbuettel/ctv-hpc) so you could PR there but I can also backport.

**Comment by wlandau** [comment]
Thanks! Just submitted https://github.com/eddelbuettel/ctv-hpc/pull/35.

**Comment by wlandau** [comment]
Thanks @eddelbuettel for merging https://github.com/eddelbuettel/ctv-hpc/pull/35!

**Comment by eddelbuettel** [comment]
Also now added here via 9facae4ba7bae670c88e85ad1971d0e3152dff68 and you beat me to the close :)
