### ISSUE TITLE
Please revert removal of _clustermq_

### ISSUE THREAD

**Issue by mschubert** [cran-task-views/HighPerformanceComputing#12]
The package is still in active development, it was just archived briefly because an update caused an issue with CRAN.

CRAN: https://cran.r-project.org/package=clustermq
Commit: https://github.com/cran-task-views/HighPerformanceComputing/commit/b05a7de2b2ca28d3b5d4df9f15303cf5705c7050

**Comment by eddelbuettel** [comment]
Thanks for the reminder, now done in https://github.com/cran-task-views/HighPerformanceComputing/commit/66236ca962fbcfb804f0330e5872a99c9234f6fa.

**Comment by mschubert** [comment]
Thank you!
