### ISSUE TITLE
Package 'rxode2random' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by kurthornik** [cran-task-views/HighPerformanceComputing#14]
Package [rxode2random](https://CRAN.R-project.org/package=rxode2random) is currently listed in CRAN Task View [HighPerformanceComputing](https://CRAN.R-project.org/view=HighPerformanceComputing) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.  See the section on _CRAN package archivals_ in the [maintenance guidelines](https://github.com/cran-task-views/ctv/blob/main/Maintenance.md) for more details.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by eddelbuettel** [comment]
Thanks. I actually removed it _in one spot_ two weeks ago but seemingly overlooked another.  My bad, will fix.

**Comment by mattfidler** [comment]
Thank you @eddelbuettel  and @kurthornik .  I should have looked at task views and removed it myself.

**Comment by eddelbuettel** [comment]
Ah no worries. I have an (old) script for that, @kurthornik has a GH Action on schedule.   My mistake was to not run the script _twice_ as `rxode2random` appeared _twice_ which is unusual for a task view but you spawned a bit of a verse so I should have checked.  All on me, but now taken care of.
