### ISSUE TITLE
Statistical Genetics Task View

### ISSUE THREAD

**Issue by privefl** [cran-task-views/HighPerformanceComputing#2]
What about this one ?
https://cran.microsoft.com/snapshot/2017-08-01/web/views/Genetics.html

**Comment by eddelbuettel** [comment]
What about it?   

And note that you filed this with HPC and it is not entire clear if that was on purpose or as your issue is lacking a bit of context. Maybe you can expand on what you wanted to achieve and/or switch to the mailing list?

**Comment by privefl** [comment]
Sorry, I did not mean to ask on the HPC one directly.
But there is no repo for the previous statgen task view.

**Comment by eddelbuettel** [comment]
Gotcha.  We had some luck within the Rocker Project moving issue tickets around if they land in the wrong spot.  It seems I could transfer it to `ctv`.  @zeileis are you on board with that?

**Comment by zeileis** [comment]
I think you can just close this here. Issue https://github.com/cran-task-views/ctv/issues/17 already discusses this in some detail.

**Comment by privefl** [comment]
Thanks both
